### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by jumanji144** [AirDog46/DreamUtils#1]
I have reviewed your code and proposed the following changes

> Code is unoptimized
> Use of utilisation for messages
> Overuse of ChatColor.translateAlternativeCodes()
> unneccesary switch casing
> missing non null checks
> unneccesary variable declaration
> other inconsistencies, like return codes

**Comment by jumanji144** [comment]
@AirDog46 
@AirDog46

**Comment by AirDog46** [comment]
Thank you for your review. After reading this I've decided to do nothing because this is old ass shit and I'm not coding anything anymore lmao xd rekt
